### ISSUE TITLE
데이터베이스 정보

### ISSUE THREAD

**Issue by xxxjjhhh** [Hyeeji/JBNU_training#1]
데이터베이스 정보 설정 파일에 노출되어 있습니다. DB 해킹 당해요,,

**Comment by 1004-1** [comment]
오~ ㅎㅎ 제가 DB를 잠가두는걸 깜빡했네요~ :) 덕분에 방금 처리 했습니다. 계정은 권한 컨트롤 되어 있어서 사실 해킹까진 쉽지 않을거라고 생각되긴 합니다만. 비용 문제가 있었거든요 :) 알려주셔서 너무 감사합니다~ 잘지내고 계시죠?
